version: "3"

services:

  mongo:
    build: 
      context: ./mongo
      dockerfile: ./Dockerfile
    environment:
      - MONGO_PORT=27018
      - MONGO_HOST=127.0.0.1
      - MONGO_DB=possibleDb
    command: mongod --port 27018
    ports:
      - "27018:27018"
      
  mongo_seed:
    build: 
      context: ./mongo-seed
      dockerfile: ./Dockerfile
    links:
        - mongo

  possible-ui:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    depends_on:
      - possible-back
    ports:
      - "5000:5000"

  possible-back:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"    
