version: "3"

services:

  mongo:
    build: 
      context: ./mongo
      dockerfile: ./Dockerfile
    command: mongod --port 27018
    ports:
      - "27018:27018"
      
  mongo-seed:
    build: ./mongo-seed
    links:
        - mongo

  possible-ui:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    depends_on:
      - possible-back
    ports:
      - "5000:5000"

  possible-back:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    links:
        - mongo
    ports:
      - "3000:3000"    
