version: "3"

services:

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - db-data:/data/db
      - mongo-config:/data/configdb
    volumes:
      - ./data/db:/data/db
    ports:
      - "27018:27018"
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  mongo_seed:
    build: 
      context: ./mongo-seed
      dockerfile: ./Dockerfile
    links:
        - mongodb

  possible-ui:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    depends_on:
      - possible-back
    ports:
      - "5000:5000"

  possible-back:
    image: 'node:8-alpine'
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongodb
    